stages:
  - test

default:
  tags:
    - extagent8

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == 'main'

test-centos7:
  stage: test
  image: centos:7
  script:
    - echo "Running unit tests for CentOS 7... This will take few minutes."
    - tests/run.sh

test-rockylinux8:
  stage: test
  image: rockylinux:8
  script:
    - echo "Running unit tests for Rocky Linux 8... This will take few minutes."
    - tests/run.sh

test-ubuntu1804:
  stage: test
  image: ubuntu:18.04
  script:
    - echo "Running unit tests for Ubuntu 18.04... This will take few minutes."
    - tests/run.sh

test-ubuntu2004:
  stage: test
  image: ubuntu:20.04
  script:
    - echo "Running unit tests for Ubuntu 20.04... This will take few minutes."
    - tests/run.sh

test-ubuntu2204:
  stage: test
  image: ubuntu:22.04
  script:
    - echo "Running unit tests for Ubuntu 22.04... This will take few minutes."
    - tests/run.sh
