stages:
  - test

default:
  tags:
    - extagent48

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == 'main'

test:
  stage: test
  image: $IMAGE
  parallel:
    matrix:
      - IMAGE: ['centos:7', 'rockylinux:8', 'rockylinux:9', 'almalinux:9', 'ubuntu:20.04', 'ubuntu:22.04'] 
  script:
    - echo "Running job \"${CI_JOB_NAME}\" with the image \"${CI_JOB_IMAGE}\"..."
    - tests/run.sh
    - echo "Successfully completed job \"${CI_JOB_NAME}\" with the image \"${CI_JOB_IMAGE}\""