stages:
  - test

default:
  tags: [extagent48]
  interruptible: true  # All the jobs can be interrupted by newer pipelines

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == 'main'

test:
  stage: test
  # Run this job using multiple images
  image: $IMAGE
  parallel:
    matrix:
      # All the images we want to use
      # rockylinux:8 is temporary excluded
      - IMAGE: ['centos:7', 'rockylinux:9', 'almalinux:9', 'ubuntu:20.04', 'ubuntu:22.04'] 
  script:
    - echo "Running job \"${CI_JOB_NAME}\" with the image \"${CI_JOB_IMAGE}\"..."
    - tests/run.sh
    - echo "Successfully completed job \"${CI_JOB_NAME}\" with the image \"${CI_JOB_IMAGE}\""