#!/bin/bash

# check for help option
if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "-?" ]; then
  echo
  echo "Usage: `basename $0` package"
  echo
  echo "- This command adds the source code of the given package from the code"
  echo "  repository to the local release directory."
  echo "  It has to be called in the local release directory."
  echo
  exit 0
fi

# check number of arguments
if [ $# -ne 1 ]; then
  echo "Usage: `basename $0` package" 1>&2
  exit 1
fi

# read arguments
PACKAGE=$1
if [ -d ${PACKAGE} ]; then
  echo "Error: The directory ${PACKAGE} already exists." 1>&2
  exit 1
fi

# update sparse-checkout file
TMP=`mktemp /tmp/belle2_tmp.XXXX`
ALL=0
DONE=0
while read -r LINE; do
  if [ "${LINE}" == "*" ]; then
    ALL=1
  fi
  if [ "${LINE}" == "!/${PACKAGE}" ]; then
    if [ ${ALL} == 1 ]; then
      DONE=1
    fi
  else
    echo "${LINE}" >> ${TMP}
    if [ "${LINE}" == "/${PACKAGE}" ]; then
      DONE=1
    fi
  fi
done < .git/info/sparse-checkout
if [ ${DONE} == 0 ]; then
  echo "/${PACKAGE}" >> ${TMP}
fi
mv -f ${TMP} .git/info/sparse-checkout

# check out package
git checkout
