#!/bin/bash

# check for help option
if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "-?" ]; then
  echo
  echo "Usage: `basename $0` directory [username]"
  echo
  echo "- This command checks out the analysis code at the given directory name."
  echo "  It also prepares the build system."
  echo "- The optional second argument can be used to specify the user name"
  echo "  if the analysis code of another user should be obtained."
  echo
  exit 0
fi

# check number of arguments
if [ $# -lt 1 -o $# -gt 2 ]; then
  echo "Usage: `basename $0` directory [username]" 1>&2
  exit 1
fi

# read arguments
DIR=$1
if [ -d ${DIR} ]; then
  echo "Error: The directory ${LOCAL_DIR} already exists." 1>&2
  exit 1
fi
USERNAME=$BELLE2_USER
if [ $# -gt 1 ]; then
  USERNAME=$2
fi


# verify that the git repository exists and is an analysis repository
ANALYSIS_NAME=${USERNAME}_${DIR}
ANALYSIS_REPOSITORY=${BELLE2_GIT_SERVER}${BELLE2_ANALYSES_PROJECT}/${ANALYSIS_NAME}.git
REPOSITORY_EXISTS_MASTER=`git ls-remote ${ANALYSIS_REPOSITORY} master 2> /dev/null | wc -l`
REPOSITORY_EXISTS_MAIN=`git ls-remote ${ANALYSIS_REPOSITORY} main 2> /dev/null | wc -l`
if [ "${REPOSITORY_EXISTS_MASTER}" = "0" ] && [ "${REPOSITORY_EXISTS_MAIN}" = "0" ]; then
  if [ "${BELLE2_GIT_ACCESS}" = "http" ]; then
    ANALYSIS_REPOSITORY=https://${BELLE2_USER}@stash.desy.de/scm/b2a/${ANALYSIS_NAME}.git
  else
    ANALYSIS_REPOSITORY=ssh://git@stash.desy.de:7999/b2a/${ANALYSIS_NAME}.git
  fi
  REPOSITORY_EXISTS_MASTER=`git ls-remote ${ANALYSIS_REPOSITORY} master 2> /dev/null | wc -l`
  REPOSITORY_EXISTS_MAIN=`git ls-remote ${ANALYSIS_REPOSITORY} main 2> /dev/null | wc -l`
  if [ "${REPOSITORY_EXISTS_MASTER}" = "0" ] && [ "${REPOSITORY_EXISTS_MAIN}" = "0" ]; then
    echo "Error: The analysis git repository ${ANALYSIS_NAME} does not exist." 1>&2
    exit 1
  fi
fi

# check out the analysis directory
git clone ${ANALYSIS_REPOSITORY} ${DIR}
if [ "$?" != "0" ]; then
  echo "Error: The checkout of the analysis repository ${ANALYSIS_NAME} failed." 1>&2
  exit 1
fi

# check whether the release exists
RELEASE=`cat ${DIR}/.analysis`
if [ ! -d ${VO_BELLE2_SW_DIR}/releases/${RELEASE} ]; then
  echo "Warning: The central release ${RELEASE} required by this analysis does not exist." 1>&2
fi

# get site-scons
pushd ${DIR} > /dev/null
ln -s ${VO_BELLE2_SW_DIR}/releases/${RELEASE}/site_scons .
ln -s site_scons/SConstruct .
popd > /dev/null

# inform user about successful completion
echo "Analysis ${ANALYSIS_NAME} for release ${RELEASE} checked out at: ${DIR}"
echo "-> change to the new directory and set up the environment: cd ${DIR}; b2setup"
