#!/bin/bash

# check for help option
if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "-?" ]; then
  echo
  echo "Usage: `basename $0` [-n|-p [-d command]] [files]"
  echo
  echo "- The b2code-style-fix tool formats the layout of C++ and python code."
  echo "  It helps developers to achieve a common style of all Belle II software."
  echo "- By default it checks all C++ and python files in the current directory and"
  echo "  its subfolders recursively."
  echo "- Individual files can be checked explicitly by giving them as argument."
  echo "  If they do not have the standard extension of .cc/.h or .py one can add"
  echo "  .cc or .py to the file name to select the check style."
  echo "- If the -n option is used, only the changes that the command would apply"
  echo "  are printed. The files are not modified. The return code gives the number"
  echo "  of files that would be changed."
  echo "- The -p option is equivalent to the -n option except that it reports the"
  echo "  pep8 and flake8 output instead of the code changes."
  echo "- The -d option can be used to specify the diff command that is called to"
  echo "  report changes. Has to be given after the -n or -p option."
  echo
  exit 0
fi

# set tools directory if unset
BELLE2_TOOLS=${BELLE2_TOOLS:-`dirname $0`}

# check astyle and its version; set its options accordingly
ASTYLE_TOOL=${BELLE2_EXTERNALS_DIR}/${BELLE2_ARCH}/common/bin/astyle
if [ ! -f "${ASTYLE_TOOL}" ]; then
  echo "Warning: astyle is not found in the externals directory."
  echo "Fixstyle will now try to use the system version."
  ASTYLE_TOOL=$(which astyle)
  if [ -z "${ASTYLE_TOOL}" ]; then
    echo "Error: astyle tool not found. Setup the externals." 1>&2
    exit 1
  fi
fi
VERSION=`LC_ALL=C ${ASTYLE_TOOL} -V 2>&1`
ASTYLE_OPTIONS=""
if [ "${VERSION}" == "Artistic Style Version 3.1" ]; then
  # for externals >= v01-11-00
  ASTYLE_OPTIONS="--indent=spaces=2 \
--convert-tabs \
--style=kr \
--attach-namespaces \
--attach-classes \
--indent-switches \
--indent-namespaces \
--indent-preprocessor \
--max-continuation-indent=60 \
--min-conditional-indent=0 \
--pad-oper \
--pad-header \
--unpad-paren \
--keep-one-line-statements \
--keep-one-line-blocks \
--suffix=none \
--align-pointer=type \
--align-reference=type \
--max-code-length=132 \
--lineend=linux \
--formatted"
elif [ "${VERSION}" == "Artistic Style Version 2.05.1" ]; then
  # for externals <= v01-10-02
  ASTYLE_OPTIONS="--indent=spaces=2 \
--convert-tabs \
--style=stroustrup \
--indent-switches \
--indent-namespaces \
--indent-preprocessor \
--max-instatement-indent=60 \
--min-conditional-indent=0 \
--pad-oper \
--pad-header \
--unpad-paren \
--keep-one-line-statements \
--keep-one-line-blocks \
--suffix=none \
--align-pointer=type \
--align-reference=type \
--max-code-length=132 \
--lineend=linux \
--formatted"
else
  echo "Error: Wrong version of astyle. Setup the latest externals version." 1>&2
  exit 1
fi

# astyle command
ASTYLE="${ASTYLE_TOOL} ${ASTYLE_OPTIONS}"

# autopep8 command
AUTOPEP8CHECK="autopep8 --aggressive --aggressive --ignore-local-config --global-config ${BELLE2_TOOLS}/pep8.cfg"
AUTOPEP8="${AUTOPEP8CHECK} --in-place"

# autopep8 command for trailing white space detection in rst files
RSTCHECK="autopep8 --aggressive --aggressive --ignore-local-config --select W291"
RSTFIX="${RSTCHECK} --in-place"

# pep8 command
PEP8="pep8 --config=${BELLE2_TOOLS}/pep8.cfg"

# flake8 command
FLAKE8="flake8 --config=${BELLE2_TOOLS}/pep8.cfg"

# diff command
DIFF="diff -u"

# count number of files that fail the check
declare -i COUNT
COUNT=0

# define function for detecting imported files
function IsImported ()
{
  DIR=`dirname $1`
  while true; do
    if [ -f ${DIR}/.imported ]; then
      echo "ignoring imported file $1"
      return 1
    fi
    NEWDIR=`dirname $DIR`
    if [ "${NEWDIR}" = "${DIR}" ]; then
      return 0
    fi
    DIR=${NEWDIR}
  done
}

# define function for C++ code style checking
function AstyleCheck ()
{
  if [ ! -L $1 ]; then
    IsImported "$1"
    if [ "$?" = 1 ]; then
      return
    fi
    RESULT=1
    TMP=`mktemp`
    TMP2=`mktemp`
    ${ASTYLE} < $1 > $TMP 2> $TMP2
    if [ "$?" = 0 ]; then
      if [ "`diff $1 $TMP | wc -l`" = "0" ]; then
        RESULT=0
      else
        echo "$1:"
        ${DIFF} $1 $TMP
      fi
    else
      cat $TMP2
    fi
    rm -f $TMP $TMP2
    COUNT+=$RESULT
  fi
}

# define function for python code checking
function Autopep8Check ()
{
  if [ ! -L $1 ]; then
    IsImported "$1"
    if [ "$?" = 1 ]; then
      return
    fi
    RESULT=1
    TMP=`mktemp`
    TMP2=`mktemp`
    ${AUTOPEP8CHECK} $1 > $TMP 2> $TMP2
    if [ "$?" = 0 ]; then
      if [ "`diff $1 $TMP | wc -l`" = "0" ]; then
        RESULT=0
      else
        echo "$1:"
        ${DIFF} $1 $TMP
      fi
    else
      cat $TMP2
    fi
    rm -f $TMP $TMP2
    COUNT+=$RESULT
  fi
}

# define function for pep8 checking
function Pep8Check ()
{
  FAIL=0
  if [ ! -L $1 ]; then
    IsImported "$1"
    if [ "$?" = 1 ]; then
      return
    fi
    TMP=`mktemp`
    ${PEP8} $1 > $TMP 2> /dev/null
    if [ "$?" != 0 ]; then
      FAIL=1
      cat $TMP
    fi
    rm -f $TMP

    # call file, disable magic checking
    LC_ALL=C file -b -m /dev/null $1 | grep "with CRLF line terminators" > /dev/null 2> /dev/null
    if [ "$?" != 1 ]; then
      FAIL=1
      echo "$1: file has DOS-style (CRLF) line-endings, please use dos2unix or your editor configuration to fix it"
    fi

    if [ "$FAIL" != 0 ]; then
      COUNT+=1
    fi
  fi
}

# define function for pep8 checking
function Flake8Check ()
{
  if [ ! -L $1 ]; then
    IsImported "$1"
    if [ "$?" = 1 ]; then
      return
    fi
    TMP=`mktemp`
    ${FLAKE8} $1 > $TMP 2> /dev/null
    if [ "$?" != 0 ]; then
      COUNT+=1
      cat $TMP
    fi
    rm -f $TMP
  fi
}

# define function for rst checking
function RstCheck ()
{
  if [ ! -L $1 ]; then
    IsImported "$1"
    if [ "$?" = 1 ]; then
      return
    fi
    RESULT=1
    TMP=`mktemp`
    TMP2=`mktemp`
    ${RSTCHECK} $1 > $TMP 2> $TMP2
    if [ "$?" = 0 ]; then
      if [ "`diff $1 $TMP | wc -l`" = "0" ]; then
        RESULT=0
      else
        echo "$1:"
        ${DIFF} $1 $TMP
      fi
    else
      cat $TMP2
      COUNT=+1
      cat $TMP
    fi
    rm -f $TMP
  fi
}

# if run in check mode
if [ "$1" = "-n" -o "$1" = "-p" ]; then

  PYTHONCHECK=Autopep8Check
  CHECKFLAKE8=false
  if [ "$1" = "-p" ]; then
    PYTHONCHECK=Pep8Check
    CHECKFLAKE8=true
  fi
  shift

  if [ "$1" = "-d" ]; then
     DIFF=$2
     shift
     shift
  fi

  # check all C++, python, and rst code below the current directory if no arguments are given
  if [ $# -lt 1 ]; then
    for i in `find . -name \\*.h`; do
      AstyleCheck $i
    done
    for i in `find . -name \\*.cc`; do
      AstyleCheck $i
    done
    for i in `find . -name \\*.py`; do
      ${PYTHONCHECK} $i
      if [ "${CHECKFLAKE8}" = true ]; then
        Flake8Check $i
      fi
    done
    for i in `find . -name \\*.rst`; do
      RstCheck $i
    done

  # check the specified files
  else
    for i in $*; do
      FILE="$i"
      CHECK=None
      if [ `echo ${FILE}| grep "\.py$"` ]; then
        CHECK=${PYTHONCHECK}
        if [ "${CHECK}" == "Pep8Check" ]; then
          CHECKFLAKE8=true
        fi
      elif [ `echo ${FILE}| grep "\.h$\|\.cc$"` ]; then
        CHECK=AstyleCheck
        CHECKFLAKE8=false
      elif [ `echo ${FILE}| grep "\.rst$"` ]; then
        CHECK=RstCheck
        CHECKFLAKE8=false
      fi
      if [ ! -e ${FILE} -a "${CHECK}" != "None" ]; then
        FILE=${FILE%.*}
      fi
      if [ ! -e ${FILE} ]; then
        echo "The file $i does not exist"
      elif [ "${CHECK}" != "None" ]; then
        ${CHECK} "${FILE}"
        if [ "${CHECKFLAKE8}" = true ]; then
          Flake8Check "${FILE}"
        fi
      else
        echo "File of unknown type not checked: $i"
      fi
    done
  fi

  # return number of files that have to be fixed
  exit $COUNT


# if run in fix mode
else
  # fix all C++, python, and rst code below the current directory if no arguments are given
  if [ $# -lt 1 ]; then

    # ask user for confirmation if there are more than 100 files
    FILES=`find . -name \\*.h; find . -name \\*.cc; find . -name \\*.py; find . -name \\*.rst`
    NFILES=`echo $FILES|wc -w`
    if [ ${NFILES} -gt 100 ]; then
      echo "There are ${NFILES} source files in or below the current directory:"
      pwd
      read -p "Are you sure you want to run fixstyle on all of them? (y/n) " -n 1 REPLY 
      echo
      if [ "$REPLY" != "y" ]; then
        exit 0
      fi
    fi

    for i in `find . -name \\*.h; find . -name \\*.cc`; do
      IsImported "$i"
      if [ "$?" = 1 ]; then
        continue
      fi
      ${ASTYLE} "$i"
    done
    for i in `find . -name \\*.py`; do
      IsImported "$i"
      if [ "$?" = 1 ]; then
        continue
      fi
      ${AUTOPEP8} "$i"
      b2code-style-check "$i" || echo "Some problems in '$i' could not be fixed, please resolve them manually."
    done
    for i in `find . -name \\*.rst`; do
      IsImported "$i"
      if [ "$?" = 1 ]; then
        continue
      fi
      ${RSTFIX} "$i"
    done

  # fix the specified files
  else
    for i in $*; do
      FILE="$i"
      CHECK=None
      if [ `echo ${FILE}| grep "\.py$"` ]; then
        CHECK=${AUTOPEP8}
      elif [ `echo ${FILE}| grep "\.h$\|\.cc$"` ]; then
        CHECK=${ASTYLE}
      elif [ `echo ${FILE}| grep "\.rst$"` ]; then
        CHECK=${RSTFIX}
      fi
      if [ ! -e ${FILE} -a "${CHECK}" != "None" ]; then
        FILE=${FILE%.*}
      fi
      if [ ! -e ${FILE} ]; then
        echo "The file $i does not exist"
      elif [ -L ${FILE} ]; then
        echo "skipping symbolic link ${FILE}"
      elif [ "${CHECK}" != "None" ]; then
        IsImported "${FILE}"
        if [ "$?" = 1 ]; then
          continue
        fi
        ${CHECK} "${FILE}"
        if [ `echo $i| grep "\.py$"` ]; then
          b2code-style-check "${FILE}" || echo "Some problems in '${FILE}' could not be fixed, please resolve them manually."
        fi
      else
        echo "File of unknown type not formatted: $i"
      fi
    done
  fi
fi
