#!/bin/bash

help() {
cat << EOF

      Usage: `basename $0` [files]

  The b2code-style-check tool checks the layout of C++ and python code
  and reports changes that the b2code-style-fix tool would apply.
  By default it checks all C++ and python files in the current directory and
  its subfolders recursively.
  Individual files can be checked explicitly by giving them as argument.

EOF
}

# check for documentation option (help + sphinx)
if [ "$1" = "--documentation" ]; then
cat << EOF

.. describe:: `basename $0`

  ::
EOF
  help
cat << EOF

  .. note:: No commits can be pushed to the server if b2code-style-check or b2code-style-fix
     report any problems.
EOF
  exit 0
fi

# check for help option
if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "-?" ]; then
  help
  exit 0
fi

# call b2code-style-fix in check mode
b2code-style-fix -p $*
