#!/bin/bash

help() {
cat << EOF

      Usage: `basename $0` [-l] [-s]

  This command lists the available packages.
  It has to be called in the local release directory.

  -l
    The responsible librarians are printed too. 
  -s
    Locally installed packages are suppressed.
    
EOF
}

# check for documentation option (help + sphinx)
if [ "$1" = "--documentation" ]; then
cat << EOF

.. describe:: `basename $0`

  ::
EOF
  help
  exit 0
fi

# check for help option
if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "-?" ]; then
  help
  exit 0
fi

# read arguments
LIST_LIBRARIANS=no
LIST_LOCAL=yes
while [ $# -gt 0 ]; do
  if [ "$1" = "-l" ]; then
    LIST_LIBRARIANS=yes
  elif [ "$1" = "-s" ]; then
    LIST_LOCAL=no
  elif [ "$1" = "-ls" -o "$1" = "-sl" ]; then
    LIST_LIBRARIANS=yes
    LIST_LOCAL=no
  else
    echo "Error: Invalid argument $1." 1>&2
    exit 1
  fi
  shift
done

# get list of packages
if [ ! -f .release ]; then
  echo "Error: Not in a release directory." 1>&2
  exit 1
fi
RELEASE=`cat .release`
if [ "${RELEASE}" = "head" ]; then
  RELEASE="HEAD"
fi

# loop over packages
PACKAGES=`git ls-tree --name-only ${RELEASE} | grep -v "^\.\|\.rst$"`
PACKAGE_LIST=""
for PACKAGE in ${PACKAGES}; do
  if [ -n "${PACKAGE}" ]; then
    if [ ${LIST_LOCAL} = no -a -d ${PACKAGE} ]; then
      continue
    fi
    if [ ${LIST_LIBRARIANS} = yes ]; then
      LIBRARIANS=`git show ${RELEASE}:${PACKAGE}/.librarians 2> /dev/null | tr "\n" "," | sed "s/,$//"`
      echo "${PACKAGE} (${LIBRARIANS})"
    else
      PACKAGE_LIST="${PACKAGE_LIST} ${PACKAGE}"
    fi
  fi
done
if [ -n "${PACKAGE_LIST}" ]; then
  echo ${PACKAGE_LIST}
fi
