#!/bin/bash
set -o pipefail

help() {
cat << EOF

      Usage: `basename $0` datatype [token]

  - This command installs or updates the given type of basf2 data.
    Supported data types are 'validation' and 'examples'.
  - The command requires that you have access to the DESY gitlab with ssh key:
      https://gitlab.desy.de
  - Alternatively a token can be used to access the repository.

EOF
}

# check for help option
if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "-?" ]; then
  help
  exit 0
fi

# check number of arguments
if [ $# -gt 2 ] || [ $# -lt 1 ]; then
  echo "Usage: `basename $0` datatype [token]" 1>&2
  echo "For more information use `basename $0` --help."
  exit 1
fi

# check for software tools setup
if [ -z "${VO_BELLE2_SW_DIR}" ]; then
  echo "Belle II software environment is not set up." 1>&2
  echo "-> source b2setup" 1>&2
  exit 1
fi


# check for optional token
GIT_URL="git@gitlab.desy.de:"
if [ $# -gt 1 ]; then
  GIT_URL="https://oauth2:${2}@gitlab.desy.de/"
fi

# get data type and corresponding directory and environment variable names
DATATYPE=$1
DIRNAME="${DATATYPE,,}-data"
ENVNAME="BELLE2_${DATATYPE^^}_DATA_DIR"

# check existence of directory and create it if missing and approved by user
if [ -n "${!ENVNAME}" ]; then
  DIR=${!ENVNAME}
  if [ ! -d ${DIR} ]; then
    echo "The environment variable ${ENVNAME} is set to ${DIR}, but the directory does not exit."
    read -p "Would you like to create it (y/n)? " -n 1 REPLY
    echo
    if [ "$REPLY" != "y" ]; then
      exit 0
    fi
    mkdir -p ${DIR}
    if [ "$?" != "0" ]; then
      echo "Error: The creation of the directory ${DIR} failed."
      echo "-> Make sure the environment variable ${ENVNAME} is set correctly and you have write access to the directory."
      exit 1
    fi
  fi
else
  DIR=${VO_BELLE2_SW_DIR}/${DIRNAME}
  if [ ! -d ${DIR} ]; then
    echo "The environment variable ${ENVNAME} is not set. The default installation directory is ${DIR}, but it does not exit."
    if [ ! -w ${VO_BELLE2_SW_DIR} ]; then
      echo "Error: No write permissions to the directory ${VO_BELLE2_SW_DIR}. Make sure the environment variable ${ENVNAME} is set correctly." 1>&2
      exit 1
    fi
    read -p "Would you like to create it (y/n)? " -n 1 REPLY
    echo
    if [ "$REPLY" != "y" ]; then
      exit 0
    fi
    mkdir -p ${DIR}
    if [ "$?" != "0" ]; then
      echo "Error: The creation of the directory ${DIR} failed."
      echo "-> Make sure the environment variable ${ENVNAME} is set correctly and you have write access to the directory."
      exit 1
    fi
  fi
fi


# connect to git repository
cd ${DIR}
if [ ! -d .git ]; then
  git clone --no-checkout ${GIT_URL}belle2/software/${DIRNAME}.git tmp
  if [ "$?" != 0 ]; then
    echo "Error: The synchronization of the ${DATATYPE} data failed." 1>&2
    echo "       Make sure you have access to the DESY gitlab." 1>&2
    exit 1
  fi
  mv tmp/.git .
  rm -rf tmp
  git lfs install
fi

# sync data
echo "Syncing ${DATATYPE} data to ${DIR}"
git fetch
if [ "$?" != 0 ]; then
  echo "Error: The synchronization of the ${DATATYPE} data failed." 1>&2
  echo "       Make sure you have access to the DESY gitlab." 1>&2
  exit 1
fi
git checkout -f main
git pull
