#!/bin/bash

NO_PROMPT=no
INSTALL_OPTIONAL=no
for i in "$@"; do
  case $i in
    --non-interactive)
      NO_PROMPT=yes
      ;;
    --optionals)
      INSTALL_OPTIONAL=y
      ;;
    *)
      cat <<EOT
Usage: b2install-prepare [--non-interactive] [--optionals]

If executed without arguments it will check if all necessary packages are
installed and if not it will ask the user if it should do it.

If --non-interactive is given it will not ask but just install the necessary
packages but not the optional ones. If --optionals is given as well it will
install everything without asking.
EOT
      exit 1
      ;;
    esac
done


# If /etc/os-release is present, read system identifer from it
OS_RELEASE_ID="<unknown>"
OS_RELEASE_ID_LIKE="<unknown>"
OS_RELEASE_VERSION="<unknown>"
if [ -f /etc/os-release ]; then
  OS_RELEASE_ID=`(source /etc/os-release && echo $ID)`
  OS_RELEASE_ID_LIKE=`(source /etc/os-release && echo $ID_LIKE)`
  OS_RELEASE_VERSION=`(source /etc/os-release && echo $VERSION_ID)`
fi


if [ `uname` = Darwin ]; then
  # Mac OS
  MISSING=""
  which make > /dev/null 
  if [ $? != 0 ]; then
    MISSING="${MISSING}, XCode command line tools"
  fi
  for TOOL in cmake fink gfortran; do
    which ${TOOL} > /dev/null
    if [ $? != 0 ]; then
      MISSING="${MISSING}, ${TOOL}"
    fi
  done
  if [ "${MISSING}" != "" ]; then
    echo "Please install the following:" `echo ${MISSING} | cut -c 2-`
    exit 1
  fi
  PACKAGES="wget"
  OPTIONALS=""
  CHECK_CMD="dpkg -s"
  SU_CMD="sudo"
  INSTALL_CMD="fink install"

elif [[ $OS_RELEASE_ID =~ ^(opensuse(-leap|-tumbleweed)?|sles)$ ]]; then
  # OpenSUSE or SUSE Linux Enterprise Server
  PACKAGES="binutils gcc gcc-c++ git make patch pattern:devel_perl
    python subversion tar gzip bzip2 xz unzip wget libpng-devel libX11-devel
    libXext-devel libXpm-devel libXft-devel ncurses-devel libopenssl-devel
    readline-devel zip java-1_8_0-openjdk-devel"
  OPTIONALS="tk-devel tcl-devel glew-devel Mesa-libGL-devel flex bison"
  CHECK_CMD="rpm -q"
  SU_CMD="su -c"
  INSTALL_CMD="zypper in"
  if [ "$NO_PROMPT" = "yes" ]; then
    INSTALL_CMD="zypper in -y"
  fi

elif [ $OS_RELEASE_ID == "ubuntu" ] || [[ $OS_RELEASE_ID_LIKE = *ubuntu* ]]; then
  # Ubuntu
  PACKAGES="binutils gcc g++ git make patch libperl-dev python subversion tar
    gzip bzip2 xz-utils unzip wget libpng-dev libx11-dev libxext-dev libxpm-dev
    libxft-dev libncurses-dev libssl-dev libreadline-dev lsof"
  OPTIONALS="tk-dev tcl-dev libglew-dev libglu-dev flex bison"
  CHECK_CMD="dpkg -s"
  SU_CMD="sudo"
  INSTALL_CMD="apt-get install"
  if [ "$NO_PROMPT" = "yes" ]; then
    INSTALL_CMD="apt-get install -y"
  fi

elif [ $OS_RELEASE_ID == "debian" ]; then
  # Debian
  PACKAGES="binutils gcc g++ git make patch libperl-dev python subversion tar
    gzip bzip2 xz-utils unzip wget libpng-dev libx11-dev libxext-dev libxpm-dev
    libxft-dev libncurses-dev libssl-dev libreadline-dev lsof zip openjdk-8-jdk"
  OPTIONALS="tk-dev tcl-dev libglew-dev libglu-dev flex bison"
  CHECK_CMD="dpkg -s"
  SU_CMD="su -c"
  INSTALL_CMD="apt-get install"
  if [ "$NO_PROMPT" = "yes" ]; then
    INSTALL_CMD="apt-get install -y"
  fi

elif [[ $OS_RELEASE_ID_LIKE = *rhel* ]] && [ $OS_RELEASE_VERSION -ge 8 ]; then
  # CentOS, RHEL starting with version 8
  PACKAGES="binutils gcc gcc-c++ git make patch perl-devel python2 subversion
    tar gzip bzip2 xz unzip wget libpng-devel libX11-devel libXext-devel
    libXpm-devel libXft-devel ncurses-devel openssl-devel readline-devel which lsof"
  OPTIONALS="tk-devel tcl-devel mesa-libGL-devel flex bison"
  CHECK_CMD="rpm -q"
  SU_CMD="su -c"
  INSTALL_CMD="dnf install"
  if [ "$NO_PROMPT" = "yes" ]; then
    INSTALL_CMD="dnf install -y"
  fi

else
  if [ ! -f /etc/redhat-release ]; then
    echo "Unknown linux distribution. Trying installation with yum..."
  fi
  # RH, SL, CentOS
  PACKAGES="binutils gcc gcc-c++ git make patch perl-devel python subversion
    tar gzip bzip2 xz unzip wget libpng-devel libX11-devel libXext-devel
    libXpm-devel libXft-devel ncurses-devel openssl-devel readline-devel which lsof"
  OPTIONALS="tk-devel tcl-devel glew-devel mesa-libGL-devel flex bison"
  CHECK_CMD="rpm -q"
  SU_CMD="su -c"
  INSTALL_CMD="yum install"
  if [ "$NO_PROMPT" = "yes" ]; then
    INSTALL_CMD="yum install -y"
  fi
fi
TEXT="already"


# check for missing packages
MISSING_PACKAGES=""
for PACKAGE in ${PACKAGES}; do
  ${CHECK_CMD} ${PACKAGE} &> /dev/null
  if [ "$?" != 0 ]; then
    MISSING_PACKAGES="${MISSING_PACKAGES} ${PACKAGE}"
  fi
done

# check for missing optional packages
MISSING_OPTIONALS=""
for PACKAGE in ${OPTIONALS}; do
  ${CHECK_CMD} ${PACKAGE} &> /dev/null
  if [ "$?" != 0 ]; then
    MISSING_OPTIONALS="${MISSING_OPTIONALS} ${PACKAGE}"
  fi
done


# ask the user to install the missing packages
if [ -n "${MISSING_PACKAGES}" ]; then
  TEXT="now"
  INSTALL_MISSING=${INSTALL_CMD}${MISSING_PACKAGES}
  if [ "${SU_CMD}" != "sudo" ]; then
    INSTALL_MISSING=\"${INSTALL_MISSING}\"
  fi
  if [ "$NO_PROMPT" = "yes" ]; then
    REPLY=y
  else
    echo "The following packages are missing:${MISSING_PACKAGES}

Please install them with the following command:

  ${SU_CMD} ${INSTALL_MISSING}

You will need root access to run this command.
"
    read -p "Would you like to execute it now (y/n)? " -n 1 REPLY
    echo
  fi
  if [ "$REPLY" = "y" ]; then
    if [ "${SU_CMD}" != "sudo" ]; then
      ${SU_CMD} "${INSTALL_CMD}${MISSING_PACKAGES}"
    else
      ${SU_CMD} ${INSTALL_MISSING}
    fi
    if [ "$?" != 0 ]; then
      exit 1
    fi
  else
    exit 1
  fi
fi

# ask the user about the optional packages
if [ -n "${MISSING_OPTIONALS}" ]; then
  TEXT="now"
  INSTALL_MISSING=${INSTALL_CMD}${MISSING_OPTIONALS}
  if [ "${SU_CMD}" != "sudo" ]; then
    INSTALL_MISSING=\"${INSTALL_MISSING}\"
  fi
  if [ "$NO_PROMPT" = "yes" ]; then
    REPLY=$INSTALL_OPTIONAL
  else
    echo "The following optional packages (required to build the event display or compile doxygen) are not installed:${MISSING_OPTIONALS}

You can install them with the following command:

  ${SU_CMD} ${INSTALL_MISSING}

You will need root access to run this command.
"
    read -p "Would you like to execute it now (y/n)? " -n 1 REPLY
    echo
  fi
  if [ "$REPLY" = "y" ]; then
    if [ "${SU_CMD}" != "sudo" ]; then
      ${SU_CMD} "${INSTALL_CMD}${MISSING_OPTIONALS}"
    else
      ${SU_CMD} ${INSTALL_MISSING}
    fi
    if [ "$?" != 0 ]; then
      exit 1
    fi
  else
    exit 0
  fi
fi


echo "
All software that is required to build the Belle II software is ${TEXT}
installed on your system.
"
