#!/bin/bash

# check for help option
if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "-?" ]; then
  echo
  echo "Usage: `basename $0` [-f]"
  echo
  echo "- This command deletes all built object files, libraries, modules, and"
  echo "  executables of your current local release."
  echo "  The prompt for confirmation can be disabled with the -f option."
  echo
  exit 0
fi

# check whether a release is set up
if [ -z "${BELLE2_LOCAL_DIR}" ]; then
  echo "Error: no local release is set up."
  exit 1
fi

# ask for confirmation, unless -f option is given
if [ "$1" != "-f" ]; then
  read -p "Delete all built files at ${BELLE2_LOCAL_DIR}? " DECISION
  if [ "${DECISION}" != "y" ]; then
    exit 0
  fi
fi

# delete the built local release files and directories
echo "Cleaning ${BELLE2_LOCAL_DIR}/build/${BELLE2_SUBDIR}"
rm -rf ${BELLE2_LOCAL_DIR}/build/${BELLE2_SUBDIR}
echo "Cleaning ${BELLE2_LOCAL_DIR}/lib/${BELLE2_SUBDIR}"
rm -rf ${BELLE2_LOCAL_DIR}/lib/${BELLE2_SUBDIR}
echo "Cleaning ${BELLE2_LOCAL_DIR}/bin/${BELLE2_SUBDIR}"
rm -rf  ${BELLE2_LOCAL_DIR}/bin/${BELLE2_SUBDIR}
echo "Cleaning ${BELLE2_LOCAL_DIR}/modules/${BELLE2_SUBDIR}"
rm -rf  ${BELLE2_LOCAL_DIR}/modules/${BELLE2_SUBDIR}
