#!/bin/bash

echo "HINT: getana is deprecated, instead use: b2analysis-get"

# check for help option
if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "-?" ]; then
  echo
  echo "Usage: `basename $0` directory [username]"
  echo
  echo "- This command checks out the analysis code at the given"
  echo "  directory name in svn."
  echo "  It also prepares the build system."
  echo "- The optional second argument can be used to specify an svn user"
  echo "  name if it differs from the local user name."
  echo
  exit 0
fi

# check number of arguments
if [ $# -lt 1 -o $# -gt 2 ]; then
  echo "Usage: `basename $0` directory [username]" 1>&2
  exit 1
fi

# read arguments
DIR=$1
if [ -d ${DIR} ]; then
  echo "Error: The directory ${LOCAL_DIR} already exists." 1>&2
  exit 1
fi
USERNAME=$BELLE2_USER
if [ $# -gt 1 ]; then
  USERNAME=$2
fi


# verify that the git repository exists and is an analysis repository
ANALYSIS_NAME=${USERNAME}_${DIR}
ANALYSIS_REPOSITORY=${BELLE2_GIT_SERVER}/${BELLE2_ANALYSES_PROJECT}/${ANALYSIS_NAME}.git
REPOSITORY_EXISTS=`git ls-remote ${ANALYSIS_REPOSITORY} master | wc -l`
if [ "${REPOSITORY_EXISTS}" = "0" ]; then
  echo "Error: The git repository ${ANALYSIS_NAME} does not exist." 1>&2
  exit 1
fi

# check out the analysis directory
git clone ${ANALYSIS_REPOSITORY} ${DIR}
if [ "$?" != "0" ]; then
  echo "Error: The checkout of the analysis repository ${ANALYSIS_NAME} failed." 1>&2
  exit 1
fi

# check whether the release exists
RELEASE=`cat ${DIR}/.analysis`
if [ ! -d ${VO_BELLE2_SW_DIR}/releases/${RELEASE} ]; then
  echo "Warning: The central release ${RELEASE} required by this analysis does not exist." 1>&2
fi

# get site-scons
pushd ${DIR} > /dev/null
ln -s ${VO_BELLE2_SW_DIR}/releases/${RELEASE}/site_scons .
ln -s site_scons/SConstruct .
popd > /dev/null

# inform user about successful completion
echo "Analysis ${ANALYSIS_NAME} for release ${RELEASE} checked out at: ${DIR}"
echo "-> change to the new directory and set up the environment: cd ${DIR}; setupana"
