#!/bin/bash

# check for help option
if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "-?" ]; then
  echo
  echo "Usage: `basename $0` directory release [username]"
  echo
  echo "- This command creates a local directory with the given name"
  echo "  for the development of analysis modules."
  echo "  It also prepares the build system and adds the analysis"
  echo "  directory to svn."
  echo "- The directory name can contain multiple levels to organize"
  echo "  the analysis code in svn."
  echo "- The second argument specifies the central release on which"
  echo "  the analysis should be based."
  echo "- The optional third argument can be used to specify an svn user"
  echo "  name if it differs from the local user name."
  echo
  exit 0
fi

# check number of arguments
if [ $# -lt 2 -o $# -gt 3 ]; then
  echo "Usage: `basename $0` directory release [username]" 1>&2
  exit 1
fi

# read arguments
DIR=$1
LOCAL_DIR=`basename ${DIR}`
if [ -d ${LOCAL_DIR} ]; then
  echo "Error: The directory ${LOCAL_DIR} already exists." 1>&2
  exit 1
fi
RELEASE=$2
if [ ! -d ${VO_BELLE2_SW_DIR}/releases/${RELEASE} ]; then
  echo "Error: The central release ${RELEASE} does not exist." 1>&2
  exit 1
fi
USERNAME=$USER
if [ $# -gt 2 ]; then
  USERNAME=$3
fi

# check svn access
svn list ${BELLE2_REPOSITORY} > /dev/null
if [ "$?" != "0" ]; then
  echo "Error: Could not access the svn repository." 1>&2
  exit 1
fi

# check whether this analysis directory already exists in svn
svn list ${BELLE2_REPOSITORY}/user/${USERNAME}/${DIR} &> /dev/null
if [ "$?" == "0" ]; then
  echo "Error: The analysis directory ${DIR} already exists in svn." 1>&2
  exit 1
fi

# create analysis directory in svn
svn mkdir --parents -m "new analysis directory ${DIR}" ${BELLE2_REPOSITORY}/user/${USERNAME}/${DIR}
if [ "$?" != "0" ]; then
  echo "Error: The creation of the analysis directory ${DIR} for user ${USERNAME} in svn failed." 1>&2
  exit 1
fi

# create local analysis directory
svn co ${BELLE2_REPOSITORY}/user/${USERNAME}/${DIR}
if [ "$?" != "0" ]; then
  echo "Error: The checkout of the analysis directory ${DIR} for user ${USERNAME} failed." 1>&2
  exit 1
fi

# get site-scons and write release version to .analysis
pushd . > /dev/null
cd ${LOCAL_DIR}
#ln -s ${VO_BELLE2_SW_DIR}/releases/${RELEASE}/site_scons .
svn co https://belle2.cc.kek.jp/svn/trunk/software/site_scons
ln -s site_scons/SConstruct .
echo ${RELEASE} > .analysis
svn add .analysis
popd > /dev/null

# inform user about successful completion
echo "New analysis directory created for ${RELEASE} release: ${DIR}"
echo "-> change to the new directory and set up the environment: cd ${DIR}; setupana"
