#!/bin/bash

# check number of arguments
if [ $# -lt 1 -o $# -gt 2 -o "$1" = "-h" ]; then
  echo "Usage: `basename $0` directory [release]" 1>&2
  exit 1
fi

# read arguments
DIR=$1
RELEASE=head
if [ $# -gt 1 ]; then
  RELEASE=$2
  svn list ${BELLE2_REPOSITORY}/releases/${RELEASE} &> /dev/null
  if [ "$?" != "0" ]; then
    echo "Error: The release ${RELEASE} does not exist." 1>&2
    exit 1
  fi
fi

# create release directory and write release version to .release
if [ -d ${DIR} ]; then
  echo "Error: The directory ${DIR} already exists." 1>&2
  exit 1
fi
mkdir ${DIR}
echo ${RELEASE} > ${DIR}/.release

# check out base directory and site-scons
if [ "${RELEASE}" = "head" ]; then
  svn co --depth=empty ${BELLE2_REPOSITORY}/trunk/software ${DIR}
  cd ${DIR}
  svn up SConstruct
  svn up site_scons
else
  svn co --depth=empty ${BELLE2_REPOSITORY}/releases/software/${RELEASE} ${DIR}
  cd ${DIR}
  svn up SConstruct
  svn up site_scons
fi

# inform user about successful completion
echo "New local directory created for ${RELEASE} release: ${DIR}"
echo "-> change to the new directory and set up the environment: cd ${DIR}; setuprel"