#!/bin/sh

# check number of arguments
if [ $# -gt 1 ]; then
  echo "Usage: `basename $0` [\"major\"/\"minor\"/\"patch\"(=default)/tag]" 1>&2
  exit 1
fi

# determine package name
PACKAGE=`pwd | awk -F/ '{print $NF}'`
svn list ${BELLE2_REPOSITORY}/${PACKAGE} &> /dev/null
if [ "$?" != "0" ]; then
  echo "Not in a package directory." 1>&2
  exit 1
fi

# check whether we are at the head of the trunk and there are no changes
svn info -R | grep URL | grep -v ${BELLE2_REPOSITORY}/${PACKAGE}/trunk &> /dev/null
if [ "$?" = "0" ]; then
  echo "Not at the trunk head. Use updatepkg head." 1>&2
  exit 1
fi
svn status -u -q | grep -v "Status against revision" &> /dev/null
if [ "$?" = "0" ]; then
  echo "There are modified files." 1>&2
  exit 1
fi

# read arguments
TAG=patch
if [ $# -gt 0 ]; then
  TAG=$1
fi

# make tag and exit if tag name is explicitly given
if [ "${TAG}" != "major" -a "${TAG}" != "minor" -a "${TAG}" != "patch" ]; then
  echo "committing tag ${TAG} of package ${PACKAGE}"
  svn copy ${BELLE2_REPOSITORY}/${PACKAGE}/trunk ${BELLE2_REPOSITORY}/${PACKAGE}/tags/${TAG} -m "tag ${TAG} of package ${PACKAGE}"
  exit 0
fi

# determine last tag
LASTTAG=`svn list ${BELLE2_REPOSITORY}/${PACKAGE}/tags | grep -e "v[0-9][0-9]-[0-9][0-9]-[0-9][0-9]" |tail -1`
if [ "${LASTTAG}" = "" ]; then
  LASTTAG=v00-00-00
fi

# determine version numbers
PATCH=`echo ${LASTTAG} | cut -c 8,9`
if [ "${TAG}" = "patch" ]; then
  PATCH=$[${PATCH}+1]
  if [ ${PATCH} -lt 10 ]; then
    PATCH="0${PATCH}"
  fi
fi
MINOR=`echo ${LASTTAG} | cut -c 5,6`
if [ "${TAG}" = "minor" ]; then
  MINOR=$[${MINOR}+1]
  if [ ${MINOR} -lt 10 ]; then
    MINOR="0${MINOR}"
  fi
  PATCH="00"
fi
MAJOR=`echo ${LASTTAG} | cut -c 2,3`
if [ "${TAG}" = "major" ]; then
  MAJOR=$[${MAJOR}+1]
  if [ ${MAJOR} -lt 10 ]; then
    MAJOR="0${MAJOR}"
  fi
  MINOR="00"
  PATCH="00"
fi

# make tag
TAG="v${MAJOR}-${MINOR}-${PATCH}"
echo "committing tag ${TAG} of package ${PACKAGE}"
svn copy ${BELLE2_REPOSITORY}/${PACKAGE}/trunk ${BELLE2_REPOSITORY}/${PACKAGE}/tags/${TAG} -m "tag ${TAG} of package ${PACKAGE}"