#!/bin/sh

# check number of arguments
if [ $# -gt 1 ]; then
  echo "Usage: `basename $0` [\"release\"/\"head\"(=default)/tag]" 1>&2
  exit 1
fi

# determine package name
PACKAGE=`pwd | awk -F/ '{print $NF}'`
svn list ${BELLE2_REPOSITORY}/${PACKAGE} &> /dev/null
if [ "$?" != "0" ]; then
  echo "Not in a package directory." 1>&2
  exit 1
fi

# read arguments
TAG=head
if [ $# -gt 0 ]; then
  TAG=$1
  if [ "${TAG}" != "head" -a "${TAG}" != "release" ]; then
    svn list ${BELLE2_REPOSITORY}/${PACKAGE}/tags/${TAG} &> /dev/null
    if [ "$?" != "0" ]; then
      echo "The tag ${TAG} does not exist." 1>&2
      exit 1
    fi
  fi
fi

# update package
if [ "${TAG}" == "release" ]; then
  if [ ! -f ../.release ]; then
    echo "Not in a release directory." 1>&2
    exit 1
  fi
  RELEASE=`cat ../.release`
  if [ "${RELEASE}" == "head" ]; then
    svn switch ${BELLE2_REPOSITORY}/${PACKAGE}/trunk
  else
    svn switch ${BELLE2_REPOSITORY}/releases/${RELEASE}/${PACKAGE}
  fi
elif [ "${TAG}" == "head" ]; then
  svn switch ${BELLE2_REPOSITORY}/${PACKAGE}/trunk
else
  svn switch ${BELLE2_REPOSITORY}/${PACKAGE}/tags/${TAG}
fi

