#!/usr/bin/env bash

# If there is nothing to commit we do nothing.
# This might happen for git commit --amend to reword the commit message
if git diff --cached --quiet; then
  exit 0
fi

# Check the tools setup
if [ -z "${BELLE2_TOOLS}" ]; then
  echo "The tools are not set up, aborting commit."
  echo "Source tools/setup_belle2 to set up the tools."
  exit 1
fi

# Check the code style
${BELLE2_TOOLS}/hooks/check_style.sh || exit 3
