#!/usr/bin/env bash

# If there is nothing to commit we do nothing.
# This might happen for git commit --amend to reword the commit message
if git diff --cached --quiet; then
  exit 0
fi

# Check the tools setup
if [ -z "${BELLE2_TOOLS}" ]; then
  echo "The tools are not set up, aborting commit."
  echo "Source tools/setup_belle2 to set up the tools."
  exit 1
fi

# To check the files to be commited we need a temporary dir as there might
# be differences between the file in the index and the file on disk
TMPDIR=`mktemp -d`
if [ $? -ne 0 ]; then
  echo "Problem creating temp dir, aborting commit."
  exit 1
fi

# Find out which files were modified
FILES_MODIFIED=`git diff --cached --name-only`
# Place a copy of the versions to be commited in the temp dir
# Add empty file with suffix .deleted for deleted files
for FILE in ${FILES_MODIFIED}; do
  git checkout-index --prefix=${TMPDIR}/ -- "${FILE}" &> /dev/null
  if [ ! -f "${TMPDIR}/${FILE}" ]; then
    mkdir -p `dirname "${TMPDIR}/${FILE}"`
    touch "${TMPDIR}/${FILE}.deleted"
  fi
done

# Add librarians and authors information
git archive -o ${TMPDIR}/access.tar --prefix=access/ HEAD `git ls-tree --name-only -r HEAD | grep ".authors\|.librarians"`

RESULT=0

# Check the code style
${BELLE2_TOOLS}/hooks/check_style.py ${TMPDIR}
if [ $? -ne 0 ]; then
  RESULT=2
fi

# Check the file sizes
${BELLE2_TOOLS}/hooks/check_size.py ${TMPDIR}
if [ $? -ne 0 ]; then
  RESULT=3
fi

# Check the access rights
BRANCH=`git branch | grep "^*" | cut -c 3-`
if [ "$BRANCH" = "master" ]; then
  if [ "$BELLE2_ACCESS_CHECK" != "no" ]; then
    ${BELLE2_TOOLS}/hooks/check_access.py ${TMPDIR}
    if [ $? -ne 0 ]; then
      if [ "$BELLE2_ACCESS_CHECK" = "yes" ]; then
        echo "=> You can set BELLE2_ACCESS_CHECK to warn to be able to commit to your local repository, BUT:"
        RESULT=4
      else
        echo "=> WARNING: You will not be able to push your changes to the central repository."
      fi
      echo "   It is recommended to either ask the librarions of the above listed packages for commit rights"
      echo "   or commit your changes to a new feature branch and then make a pull request to the librarians."
    fi
  fi
fi

# Clean up the temp dir
rm -r ${TMPDIR}

# Return check result
if [ $RESULT -ne 0 ]; then
  echo
  echo "*** Commit aborted (see reasons above) ***"
fi

exit 10
exit $RESULT
