#!/usr/bin/env bash

# If there is nothing to commit we do nothing.
# This might happen for git commit --amend to reword the commit message
if git diff --cached --quiet; then
  exit 0
fi

# Check the tools setup
if [ -z "${BELLE2_TOOLS}" ]; then
  echo "The tools are not set up, aborting commit."
  echo "Source tools/setup_belle2 to set up the tools."
  exit 1
fi

# To check the files to be commited we need a temporary dir as there might
# be differences between the file in the index and the file on disk
TMPDIR=`mktemp -d`
if [ $? -ne 0 ]; then
  echo "Problem creating temp dir, aborting commit."
  exit 2
fi

# Find out which files were modified
FILES_MODIFIED=`git diff --cached --name-only`
# Place a copy of the versions to be commited in the temp dir
git checkout-index --prefix=${TMPDIR}/ -- ${FILES_MODIFIED}
# Add empty file with suffix .deleted for deleted files
for FILE in ${FILES_MODIFIED}; do
  if [ ! -f "${TMPDIR}/${FILE}" ]; then
    touch "${TMPDIR}/${FILE}.deleted"
  fi
done

RESULT=0

# Check the code style
${BELLE2_TOOLS}/hooks/check_style.sh ${TMPDIR}
if [ $? -ne 0 ]; then
  echo "=> Please run 'fixstyle' on the files listed above and 'git add' them to your commit again."
  RESULT=3
fi

# Check the file sizes
${BELLE2_TOOLS}/hooks/check_size.py ${TMPDIR}
if [ $? -ne 0 ]; then
  RESULT=4
fi

# Clean up the temp dir
rm -r ${TMPDIR}

# Return check result
if [ $RESULT -ne 0 ]; then
  echo "*** Commit aborted ***"
fi

exit 1

exit $RESULT
